import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Todo App",
  description: "Generated by sksagar497",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-orange-400">
        <div>
          <h1 className="text-center text-5xl pt-10 font-bold">
            Todo Application
          </h1>
        </div>
        {children}
      </body>
    </html>
  );
}
