version: "3"
services:
  api:
    image: node:20.11.0
    command: sh -c 'npm install && npm run server --env=dev'
    container_name: backend_core_api
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3005:3005"
    depends_on:
      - db
  db:
    container_name: backend_core_db
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - pg-dataset:/var/lib/postgresql/data

volumes:
  pg-dataset:
  cache:
    driver: local
